# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200519_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='phone_number',
        ),
    ]
